### ISSUE TITLE
Getting animation related error while navigating to another page

### ISSUE THREAD

**Issue by kishkk** [DashboardPack/architectui-angular-theme-free#1]
Hi

I am getting animation related error when trying to navigate to another page.

![Capture](https://user-images.githubusercontent.com/5027258/59382406-420aab00-8d7b-11e9-969a-81410f843c09.PNG)

Please help

Thanks 
Kishor

**Comment by DPTeamMember** [comment]
Hello @kishkk 

We have resolved this issue in our latest release of angular 11, Please review.

Thank you.
